GET http://localhost:3000/posts

###

POST http://localhost:3000/users
Content-Type: application/json

{
    "first_name": "Joe",
    "last_name": "Bloggs",
    "username": "JBloggs123",
    "password": "password"
}

###

GET http://localhost:3000/users/6629b05bbbb311f7f26fcf83

###

GET http://localhost:3000/posts

###

POST http://localhost:3000/posts
Content-Type: application/json

{
    "title": "Test post2",
    "content": "content",
    "user": "6629b05bbbb311f7f26fcf83"
}

###

DELETE http://localhost:3000/posts/6629d46e2f78dbff37ea107c

###

PUT http://localhost:3000/posts/6629d46e2f78dbff37ea107c
Content-Type: application/json

{
    "title": "Test post4",
    "content": "content",
    "user": "6629b05bbbb311f7f26fcf83"
}

###

POST http://localhost:3000/posts/6629d20c9f85378189f68ca9/comments
Content-Type: application/json

{
    "name": "John",
    "message": "Nice post"
}

###

GET http://localhost:3000/posts/6629d20c9f85378189f68ca9/comments

###

POST http://localhost:3000/login

###

POST http://localhost:3000/signup